artifacts_root: artifacts

summarization:
  model_path: facebook/bart-large-cnn
  max_length: 130
  min_length: 30
  do_sample: 0

categorization:
  threshold: 0.5
  model_path: kartashoffv/news_topic_classification

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 
  local_dir_file: 
  unzip_dir: 

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: 
  ALL_REQUIRED_FILES: []

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/dataset
  tokenizer_name: 

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/dataset
  model_ckpt: 

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/
  model_path: artifacts/model_trainer/model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv